/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication2;

import javaapplication2.models.CategoryProduct;
import javaapplication2.models.Product;
import java.util.ArrayList;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
//import com.itextpdf.text.Element;
// Adding table in a pdf using java
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
  
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.BlockElement;
import com.itextpdf.layout.element.Cell;
import com.itextpdf.layout.element.Table;
import com.itextpdf.layout.properties.TextAlignment;
import java.io.FileNotFoundException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author MYPC
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */

        static ArrayList<Product> productList;
        static ListOfItems listOfItems; 
      CategoryProduct categoryProduct = new CategoryProduct(); 
      
         public Menu() {
            
  
        
        initComponents();
                      productList = new ArrayList<>();
listOfItems = new ListOfItems(productList);
        productList.add(new Product("Coca-Cola",34,categoryProduct.beverages ));
        productList.add(new Product("Sprite",35,categoryProduct.beverages ));
        productList.add(new Product("Mountain Dew",34,categoryProduct.beverages ));
        productList.add(new Product("Ligo Sardines",25,categoryProduct.cannedFoodPack ));
        productList.add(new Product("Pancit Canton",16.5, categoryProduct.cannedFoodPack));
        listOfItems.getListOfItems().forEach((product) -> {
            jComboBox2.addItem(product.nameOfProduct);
            
        });
       jComboBox1.addItem(categoryProduct.beverages);
    jComboBox1.addItem(categoryProduct.cereal);
    jComboBox1.addItem(categoryProduct.frozenFood);
    jComboBox1.addItem(categoryProduct.cannedFoodPack);
        initialization(productList,categoryProduct, listOfItems);
        AutoCompleteDecorator.decorate(jComboBox2);
        
    }
    public void initialization(ArrayList<Product> productList, CategoryProduct categoryProduct,ListOfItems listOfItems){

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        SpinnerModel modeltau = new SpinnerNumberModel(1, 1, 20, 1);
        jQuantityItem = new javax.swing.JSpinner(modeltau);
        jTextPrice = new javax.swing.JTextField();
        jtextGRANDTOTAL = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jTextPriceTotal = new javax.swing.JTextField();
        jTextPAYMENT = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product", "Price", "Quantity", "Total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(153, 255, 153));
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 102, 102));
        jButton2.setText("Remove");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jQuantityItem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jQuantityItem.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jQuantityItemStateChanged(evt);
            }
        });

        jtextGRANDTOTAL.setEnabled(false);
        jtextGRANDTOTAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextGRANDTOTALActionPerformed(evt);
            }
        });

        jButton3.setText("PRINT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextPAYMENT.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTextPAYMENTInputMethodTextChanged(evt);
            }
        });
        jTextPAYMENT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPAYMENTActionPerformed(evt);
            }
        });

        jCheckBox1.setText("With 20% DISCOUNT?");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jQuantityItem, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextPriceTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(216, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextPAYMENT, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtextGRANDTOTAL, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jQuantityItem, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextPriceTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtextGRANDTOTAL, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextPAYMENT, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(112, 112, 112))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.out.println(jComboBox2.getSelectedItem());
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel(); 
        double totalPrice = Double.parseDouble(jTextPrice.getText()) * (Integer)(jQuantityItem.getValue()) ;
       jTextPriceTotal.setText(""+(totalPrice));
        model.addRow(new Object[]{jComboBox2.getSelectedItem(),jTextPrice.getText(),jQuantityItem.getValue(), totalPrice});
       getTotalSum();
    }//GEN-LAST:event_jButton1ActionPerformed
    public double getTotalSum(){
    double sum = 0;
    for(int i=0; i<jTable1.getRowCount(); i++){
        sum = sum + Double.parseDouble(jTable1.getValueAt(i, 3).toString());
    }
    jtextGRANDTOTAL.setText(sum+"");
    return sum;
    }
    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
       // ArrayList<Product> productList = new ArrayList<Product>();
       
        double price = productList.get(jComboBox2.getSelectedIndex()).priceOfProduct;
        
        jTextPrice.setText(""+price);
        int quantity = (Integer)jQuantityItem.getValue();
        
        jTextPriceTotal.setText(""+(price*quantity));
    }//GEN-LAST:event_jComboBox2ActionPerformed
    
    public void printTheTotal(){
    }
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            try {
                printLORDPleaseHelp();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jQuantityItemStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jQuantityItemStateChanged
        int quantity = (Integer)jQuantityItem.getValue();
        double price = Double.parseDouble(jTextPrice.getText());
        jTextPriceTotal.setText(""+(price*quantity));
    }//GEN-LAST:event_jQuantityItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel defaultTableModel = (DefaultTableModel) jTable1.getModel();
        if(jTable1.getSelectedRowCount()==1){
        defaultTableModel.removeRow(jTable1.getSelectedRow());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jtextGRANDTOTALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextGRANDTOTALActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextGRANDTOTALActionPerformed

    private void jTextPAYMENTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPAYMENTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPAYMENTActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
       double sum=  getTotalSum();
        if(jCheckBox1.isSelected()){
       
       double newSum = sum- sum*0.2;
        jtextGRANDTOTAL.setText(""+newSum);
        }
        else{
            jtextGRANDTOTAL.setText(""+sum);
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jTextPAYMENTInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTextPAYMENTInputMethodTextChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextPAYMENTInputMethodTextChanged

    public void printLORDPleaseHelp() throws FileNotFoundException{
         double sum=  getTotalSum();
         double vat = (getTotalSum()/1.12)*0.12;
         double VATAble = getTotalSum() - ((getTotalSum()/1.12)*0.12);
         SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy HH-mm-ss");
String string  = dateFormat.format(new Date());
    String file
            = "C:/Invoice/Invoice"+string+ ".pdf";
  
        // Step-1 Creating a PdfDocument object
        PdfDocument pdfDoc
            = new PdfDocument(new PdfWriter(file));
  
        // Step-2 Creating a Document object
        Document doc = new Document(pdfDoc);
        // Step-3 Creating a table
        
        
        float[] columnWidths = {200f, 100f, 100f, 200f};
        Table table = new Table(columnWidths);
        
        table.setFontSize(20f);
        
        // Step-4 Adding cells to the table
        for(int i=0; i<jTable1.getRowCount(); i++){
            table.addCell(jTable1.getValueAt(i,0).toString());
            table.addCell(jTable1.getValueAt(i,1).toString());
            table.addCell(jTable1.getValueAt(i,2).toString());
            table.addCell(jTable1.getValueAt(i,3).toString());
        }
        
        table.addCell("Total");
        table.addCell("");
        table.addCell("");
        table.addCell("PHP. "+sum);
        if(jCheckBox1.isSelected()){       
            double newSum = sum- sum*0.2;
             table.addCell("Total with 20% Discount");
             table.addCell("");
             table.addCell("");
             table.addCell("PHP. "+newSum);
        }
        table.addCell("Cash");
        table.addCell("");
        table.addCell("");
        table.addCell("PHP. "+(jTextPAYMENT.getText()));
        table.addCell("Change");
        table.addCell("");
        table.addCell("");
        table.addCell("PHP. "+(Double.parseDouble(jTextPAYMENT.getText()) - sum ));
        table.addCell("VATable");
        table.addCell("");
        table.addCell("");
        table.addCell("PHP. "+(String.format("%.2f", VATAble)));
        table.addCell("VAT");
        table.addCell("");
        table.addCell("");
        table.addCell("PHP. "+(String.format("%.2f", vat)));
        
        
       
        
        
        
        
        
        
        doc.setTextAlignment(TextAlignment.CENTER);
  

        
        // Step-6 Adding Table to document
        doc.add(table);
  
        // Step-7 Closing the document
        doc.close();
        System.out.println("Table created successfully..");
    JOptionPane.showMessageDialog(this,"Go to C: Drive and check the file","Alert",JOptionPane.WARNING_MESSAGE); 
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JSpinner jQuantityItem;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextPAYMENT;
    private javax.swing.JTextField jTextPrice;
    private javax.swing.JTextField jTextPriceTotal;
    private javax.swing.JTextField jtextGRANDTOTAL;
    // End of variables declaration//GEN-END:variables
}
